openapi: 3.0.0
info:
  title: Youtube API
  version: 1.0.0
  description: Youtube API documentation

tags:
  - name: Testing
    description: API for clearing the database
  - name: Videos
    description: API for managing videos
